# Generated by Django 4.1 on 2022-09-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contactline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['name'], 'verbose_name': 'Контент'},
        ),
    ]
