# Generated by Django 4.1 on 2022-09-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_videocontent_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoContent',
            new_name='Content',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['name'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контенты'},
        ),
    ]
