# Generated by Django 4.1 on 2022-09-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_content_link_alter_content_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
            ],
            options={
                'verbose_name': 'Слоганы в вупусках',
                'verbose_name_plural': 'Слоганы в вупусках',
            },
        ),
        migrations.CreateModel(
            name='JournalTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
            ],
            options={
                'verbose_name': 'Слоганы о журнале',
                'verbose_name_plural': 'Слоганы о журнале',
            },
        ),
        migrations.CreateModel(
            name='NewsTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
            ],
            options={
                'verbose_name': 'Слоганы о журнале',
                'verbose_name_plural': 'Слоганы в новостях',
            },
        ),
        migrations.AlterModelOptions(
            name='maintagline',
            options={'verbose_name': 'Слоганы в главной странице', 'verbose_name_plural': 'Слоганы в главной странице'},
        ),
    ]
