# Generated by Django 4.1.1 on 2022-09-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_newscircletaglineone'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscircletaglineone',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AddField(
            model_name='newscircletaglineone',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
        migrations.AddField(
            model_name='newscircletaglineone',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово'),
        ),
    ]
