# Generated by Django 4.1.1 on 2022-09-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_bluetagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCircleTaglineTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Круг2',
                'verbose_name_plural': 'Круг2',
            },
        ),
    ]
