# Generated by Django 4.1.1 on 2022-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_newscircletaglineone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Красные поля главной страницы',
                'verbose_name_plural': 'Красные поля главной страницы',
            },
        ),
    ]
