# Generated by Django 4.1.1 on 2022-09-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_redtagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutJournalTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
            ],
            options={
                'verbose_name': 'Слова на странице о журнале',
                'verbose_name_plural': 'Слова на странице о журнале',
            },
        ),
        migrations.CreateModel(
            name='ArticlesTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
            ],
            options={
                'verbose_name': 'Слова на странице выпусках',
                'verbose_name_plural': 'Слова на странице выпусках',
            },
        ),
        migrations.CreateModel(
            name='NewsTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
            ],
            options={
                'verbose_name': 'Слова на странице новостях',
                'verbose_name_plural': 'Слова на странице новостях',
            },
        ),
        migrations.AlterModelOptions(
            name='maintagline',
            options={'verbose_name': 'Слова в главной странице', 'verbose_name_plural': 'Слова в главной странице'},
        ),
    ]
