# Generated by Django 4.1.1 on 2022-09-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_aboutjournaltagline_articlestagline_newstagline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название текста')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название текста')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название текста')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название текста')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
                ('text_en', models.TextField(null=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='project-images', verbose_name='Изображение')),
                ('pdf', models.FileField(upload_to='')),
                ('word', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Документация для авторов',
                'verbose_name_plural': 'Документация для авторов',
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название_видео')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название_видео')),
                ('title_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название_видео')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название_видео')),
                ('video', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('video_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('video_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('video_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content')),
            ],
            options={
                'verbose_name': 'Видео_Контент',
                'ordering': ['title'],
            },
        ),
    ]
