# Generated by Django 4.1.1 on 2022-09-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_journalsfiles_videocontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='articlesarchive',
            name='category_name',
        ),
        migrations.AddField(
            model_name='authorcategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='authorcategory',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='authorcategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='CategoriesForArchieved',
        ),
    ]
