# Generated by Django 4.1.1 on 2022-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_articles_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutJournalLowPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание')),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_ky', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content')),
            ],
            options={
                'verbose_name': 'Описание о журнале в нижней части',
                'verbose_name_plural': 'Описание о журнале в нижней части',
            },
        ),
    ]
