# Generated by Django 4.1.1 on 2022-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_aboutjournallowpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutJournalCircleTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст1')),
                ('title1_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст1')),
                ('title1_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст1')),
                ('title1_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст1')),
                ('title2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст2')),
                ('title2_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст2')),
                ('title2_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст2')),
                ('title2_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст2')),
                ('title3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст3')),
                ('title3_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст3')),
                ('title3_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст3')),
                ('title3_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст3')),
                ('title4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст4')),
                ('title4_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст4')),
                ('title4_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст4')),
                ('title4_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст4')),
                ('title5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст5')),
                ('title5_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст5')),
                ('title5_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст5')),
                ('title5_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст5')),
                ('title6', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст6')),
                ('title6_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст6')),
                ('title6_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст6')),
                ('title6_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст6')),
                ('title7', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст7')),
                ('title7_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст7')),
                ('title7_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст7')),
                ('title7_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст7')),
            ],
            options={
                'verbose_name': 'Слова на планете странице о журнале',
                'verbose_name_plural': 'Слова на планете странице о журнале',
            },
        ),
        migrations.DeleteModel(
            name='AboutJournalTagline',
        ),
    ]
