# Generated by Django 4.1.1 on 2022-09-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_aboutjournallowpart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForAuthorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Авторам - Заголовок',
                'verbose_name_plural': 'Авторам - Заголовок',
            },
        ),
        migrations.RenameModel(
            old_name='Authors',
            new_name='ForAuthor',
        ),
        migrations.RenameModel(
            old_name='AuthorCategory',
            new_name='ForAuthorCategory',
        ),
        migrations.AlterModelOptions(
            name='forauthor',
            options={'verbose_name': 'Авторам - Описание', 'verbose_name_plural': 'Авторам - Описание'},
        ),
    ]
