# Generated by Django 4.1.1 on 2022-09-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_forauthor_text_alter_forauthor_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forauthor',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='forauthor',
            name='word',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
