# Generated by Django 4.1.1 on 2022-09-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintagline',
            name='title',
        ),
        migrations.RemoveField(
            model_name='maintagline',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='maintagline',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='maintagline',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название главной страницы'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title1_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название главной страницы'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title1_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название главной страницы'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title1_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название главной страницы'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение описание1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title2_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение описание1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение описание1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение описание1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение описание2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title3_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение описание2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title3_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение описание2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title3_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение описание2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title4_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title4_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title4_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Epos1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title5_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Epos1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title5_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Epos1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title5_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Epos1'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title6_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title6_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title6_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title7',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title7_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title7_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title7_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manas2'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title8',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название картинок'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title8_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название картинок'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title8_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название картинок'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title8_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название картинок'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title9',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отправки сообщения'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title9_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отправки сообщения'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title9_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отправки сообщения'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title9_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отправки сообщения'),
        ),
    ]
