# Generated by Django 4.1.1 on 2022-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_maintagline_title10_alter_maintagline_title9_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintagline',
            name='title10_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отправки сообщения'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title10_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отправки сообщения'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title10_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отправки сообщения'),
        ),
    ]
