# Generated by Django 4.1.1 on 2022-09-17 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_maintagline_title10_en_maintagline_title10_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintagline',
            name='title10',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Название отправки сообщения'),
        ),
        migrations.AlterField(
            model_name='maintagline',
            name='title10_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Название отправки сообщения'),
        ),
        migrations.AlterField(
            model_name='maintagline',
            name='title10_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Название отправки сообщения'),
        ),
        migrations.AlterField(
            model_name='maintagline',
            name='title10_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Название отправки сообщения'),
        ),
    ]
