# Generated by Django 4.1.1 on 2022-09-17 16:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_aboutjournalcircletagline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutjournallowpart',
            name='statistic_title_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Навзание поле статистики'),
        ),
        migrations.AddField(
            model_name='aboutjournallowpart',
            name='statistic_title_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Навзание поле статистики'),
        ),
        migrations.AddField(
            model_name='aboutjournallowpart',
            name='statistic_title_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Навзание поле статистики'),
        ),
    ]
