# Generated by Django 4.1.1 on 2022-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_articlescircletagline_alter_articles_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_blue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Синяя кнопка')),
                ('red_blue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Красная кнопка')),
                ('archived_title', models.CharField(max_length=200, verbose_name='Заголовок архива')),
            ],
            options={
                'verbose_name': 'Выпуски - страница',
                'verbose_name_plural': 'Выпуски - страница',
            },
        ),
    ]
