# Generated by Django 4.1.1 on 2022-09-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_articlepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='red_blue',
            new_name='button_red',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='archived_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок архива'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='archived_title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок архива'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='archived_title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок архива'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='button_blue_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Синяя кнопка'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='button_blue_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Синяя кнопка'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='button_blue_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Синяя кнопка'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='button_red_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Красная кнопка'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='button_red_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Красная кнопка'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='button_red_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Красная кнопка'),
        ),
    ]
