# Generated by Django 4.1.1 on 2022-09-18 08:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_rename_red_blue_articlepage_button_red_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='statistic_pre_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Второе заглавие'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст статистики'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Заглавие статистики'),
        ),
    ]
