# Generated by Django 4.1.1 on 2022-09-18 08:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_articlepage_statistic_pre_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='statistic_pre_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Второе заглавие'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_pre_title_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Второе заглавие'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_pre_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Второе заглавие'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст статистики'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_text_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст статистики'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст статистики'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_title_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Заглавие статистики'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_title_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Заглавие статистики'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='statistic_title_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Заглавие статистики'),
        ),
    ]
