# Generated by Django 4.1.1 on 2022-09-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_articlepage_statistic_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscircletaglineone',
            options={'verbose_name': 'Выпуски - Круг1', 'verbose_name_plural': 'Выпуски - Круг1'},
        ),
        migrations.AlterModelOptions(
            name='newscircletaglinetwo',
            options={'verbose_name': 'Выпуски - Круг2', 'verbose_name_plural': 'Выпуски - Круг2'},
        ),
    ]
