# Generated by Django 4.1.1 on 2022-09-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_newscircletaglineone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscircletaglineone',
            options={'verbose_name': 'Новости - Круг1', 'verbose_name_plural': 'Новости - Круг1'},
        ),
        migrations.AlterModelOptions(
            name='newscircletaglinetwo',
            options={'verbose_name': 'Новости - Круг2', 'verbose_name_plural': 'Новости - Круг2'},
        ),
    ]
