# Generated by Django 4.1.1 on 2022-09-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_newscircletaglineone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscircletaglineone',
            options={'verbose_name': 'Выпуск - Круг1', 'verbose_name_plural': 'Выпуск - Круг1'},
        ),
        migrations.AlterModelOptions(
            name='newscircletaglinetwo',
            options={'verbose_name': 'Выпуск - Круг2', 'verbose_name_plural': 'Выпуск - Круг2'},
        ),
        migrations.AddField(
            model_name='articlepage',
            name='number_blue1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цифры в синей статистики1'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='number_blue2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цифры в синей статистики2'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='red_blue1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цифры в красной статистики1'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='red_blue2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цифры в красной статистики2'),
        ),
    ]
