# Generated by Django 4.1.1 on 2022-09-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_news_text_alter_news_text_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['title'], 'verbose_name': 'Видео_Контент', 'verbose_name_plural': 'Видео_Контент'},
        ),
    ]
