# Generated by Django 4.1.1 on 2022-09-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_videocontent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'verbose_name': 'Новости - Контент', 'verbose_name_plural': 'Новости - Контент'},
        ),
    ]
