# Generated by Django 4.1.1 on 2022-09-19 18:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_videocontent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресс')),
                ('address_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресс')),
                ('address_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресс')),
                ('address_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресс')),
                ('phone_number', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Номера')),
                ('phone_number_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Номера')),
                ('phone_number_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Номера')),
                ('phone_number_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Номера')),
                ('mail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Почта')),
                ('mail_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Почта')),
                ('mail_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Почта')),
                ('mail_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_en',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_ky',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_ru',
        ),
    ]
