# Generated by Django 4.1.1 on 2022-09-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_contacts_remove_videocontent_video_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='ImagesContent',
        ),
    ]
