# Generated by Django 4.1.1 on 2022-09-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_delete_gallery_delete_imagescontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'О журнале - Статистика', 'verbose_name_plural': 'О журнале - Статистика'},
        ),
    ]
