# Generated by Django 4.1.1 on 2022-09-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_statistic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalsfiles',
            options={'verbose_name': 'Авторам - Документы', 'verbose_name_plural': 'Авторам - Документы'},
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='image',
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='text',
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='title',
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='journalsfiles',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='journalsfiles',
            name='pdf_en',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='journalsfiles',
            name='pdf_ky',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='journalsfiles',
            name='pdf_ru',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='journalsfiles',
            name='word_en',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='journalsfiles',
            name='word_ky',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='journalsfiles',
            name='word_ru',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='journalsfiles',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='journalsfiles',
            name='word',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
