# Generated by Django 4.1.1 on 2022-09-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_journalsfiles_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bluetagline',
            options={'verbose_name': 'Главная - Эквалайзер - Синий', 'verbose_name_plural': 'Главная - Эквалайзер - Синий'},
        ),
        migrations.AlterModelOptions(
            name='redtagline',
            options={'verbose_name': 'Главная - Эквалайзер - Красный', 'verbose_name_plural': 'Главная - Эквалайзер - Красный'},
        ),
    ]
