# Generated by Django 4.1.1 on 2022-09-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_delete_articlestagline_alter_maintagline_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsTagline',
        ),
    ]
