# Generated by Django 4.1.1 on 2022-09-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_articles_options_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintagline',
            name='title11',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Мнения экспертов'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title11_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Мнения экспертов'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title11_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Мнения экспертов'),
        ),
        migrations.AddField(
            model_name='maintagline',
            name='title11_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Мнения экспертов'),
        ),
    ]
