# Generated by Django 4.1.1 on 2022-09-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_maintagline_title11_maintagline_title11_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Твиттер'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='vk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вконтакте'),
        ),
    ]
